-- MySQL Script generated by MySQL Workbench
-- Sun Mar 18 20:40:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema skip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema skip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `skip` DEFAULT CHARACTER SET utf8 ;
USE `skip` ;

-- -----------------------------------------------------
-- Table `skip`.`cuisine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skip`.`cuisine` ;

CREATE TABLE IF NOT EXISTS `skip`.`cuisine` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `skip`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skip`.`customer` ;

CREATE TABLE IF NOT EXISTS `skip`.`customer` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `address` VARCHAR(500) NOT NULL,
  `creation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `skip`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skip`.`store` ;

CREATE TABLE IF NOT EXISTS `skip`.`store` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(500) NULL DEFAULT NULL,
  `cuisine_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_cuisine_idx` (`cuisine_id` ASC),
  CONSTRAINT `FK_cuisine`
    FOREIGN KEY (`cuisine_id`)
    REFERENCES `skip`.`cuisine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `skip`.`torder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skip`.`torder` ;

CREATE TABLE IF NOT EXISTS `skip`.`torder` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `customer_id` BIGINT(20) NOT NULL,
  `delivery_address` VARCHAR(500) NOT NULL,
  `contact` VARCHAR(50) NOT NULL,
  `store_id` BIGINT(20) NOT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `status` VARCHAR(50) NOT NULL,
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `FK_order_store_idx` (`store_id` ASC),
  INDEX `FK_order_customer_idx` (`customer_id` ASC),
  CONSTRAINT `FK_order_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `skip`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_order_store`
    FOREIGN KEY (`store_id`)
    REFERENCES `skip`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `skip`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skip`.`product` ;

CREATE TABLE IF NOT EXISTS `skip`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `store_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_store_idx` (`store_id` ASC),
  CONSTRAINT `FK_store`
    FOREIGN KEY (`store_id`)
    REFERENCES `skip`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `skip`.`order_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skip`.`order_item` ;

CREATE TABLE IF NOT EXISTS `skip`.`order_item` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT(20) NULL DEFAULT NULL,
  `product_id` BIGINT(20) NOT NULL,
  `price` DOUBLE NOT NULL,
  `quantity` BIGINT(20) NOT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_order_product_idx` (`product_id` ASC),
  INDEX `FK_order_item_order_idx` (`order_id` ASC),
  CONSTRAINT `FK_order_item_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `skip`.`torder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_order_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `skip`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
